name: Lint
on: [pull_request]

jobs:
  check-lint-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: ./typescript
      - name: Ensure Linting
        working-directory: ./typescript
        run: |
          pnpm install --frozen-lockfile
          pnpm lint:check

  check-lint-examples-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: ./examples/typescript
      - name: Ensure Linting
        working-directory: ./examples/typescript
        run: |
          pnpm install --frozen-lockfile
          pnpm lint:check