name: Publish x402 to PyPI

on:
  workflow_dispatch:

jobs:
  publish-pypi-x402:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/x402
    environment:
      name: pypi
      url: https://pypi.org/p/x402
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync

      - name: Build package
        id: build
        run: |
          uv build
          echo "version=$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml)" >> $GITHUB_OUTPUT

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          packages-dir: python/x402/dist/
          password: ${{ secrets.PYPI_X402_TOKEN }}
